name: Registry Importer

on:
  push:
    branches: [trh/daily-import]

jobs:
  importer:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PACCHETTIBOTTI_TOKEN }}
      PACCHETTIBOTTI_TOKEN: ${{ secrets.PACCHETTIBOTTI_TOKEN }}
      SPACES_KEY: ${{ secrets.SPACES_KEY }}
      SPACES_SECRET: ${{ secrets.SPACES_SECRET }}

    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PACCHETTIBOTTI_TOKEN }}
          # ref: master

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('./ci/**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache PureScript dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('./ci/**/*.dhall') }}
          path: |
            ./ci/.spago
            ./ci/output

      - name: Cache importer artifacts
        uses: actions/cache@v2
        with:
          # This cache directory is meant to be essentially permanent, with cache
          # expiry implemented in code.
          key: ${{ runner.os }}-importer-0
          path: |
            ./ci/.cache

      - name: Install Nix
        uses: cachix/install-nix-action@v16
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ env.GITHUB_TOKEN }}

      - name: "Run registry-importer"
        run: |
          cd ci
          nix develop --command 'registry-install'
          git config user.name "PacchettiBotti"
          git config user.email "<pacchettibotti@ferrai.io"
          nix develop --command 'registry-importer'
